"""Generate 06b_calibration_residential_companies.ipynb.

Follows 06a_calibration_schools.ipynb's method for the two remaining
uncalibrated Brazil asset types:
- Residential (impf 101 loss / 102 affected), obs: 'Residential'
- Companies   (impf 201 loss / 202 affected), obs: 'Business: All'

Differences from 06a (documented in the notebook):
- One parametrized loop over both asset types instead of copy-pasted cells.
- Coarser loss-search grid (same bounds; ~1,300 instead of ~5,100 runs per
  asset — Residential has 20,187 exposure points vs 122 schools).
- The calibrated Entity Excel files are written automatically (06a prints a
  table to copy by hand); intensity_unit is written as 'days' (the true unit).

Run from the notebooks/ directory with the climada_env environment.
"""
import nbformat

DST = "06b_calibration_residential_companies.ipynb"

cells = []
md = lambda s: cells.append(nbformat.v4.new_markdown_cell(s))
code = lambda s: cells.append(nbformat.v4.new_code_cell(s))

md(
    "# Calibration: Residential and Companies\n\n"
    "This notebook calibrates impact functions for the two remaining uncalibrated asset "
    "types in the Brazil starter pack, following the method of "
    "`06a_calibration_schools.ipynb`:\n\n"
    "- **Residential** (loss function 101, affected function 102) — calibrated against the "
    "Porto Alegre 'Affected' count and the IDB economic-loss figure for residential "
    "buildings\n"
    "- **Companies** (loss function 201, affected function 202) — calibrated against the "
    "'Business: All' observations\n\n"
    "The approach per asset type is identical to 06a:\n"
    "1. a step-function grid search for the *affected* count, and\n"
    "2. a 2-D grid search (max intensity × max damage) scaling the first-guess loss curve, "
    "followed by an expert-judgement filter, for *economic loss*.\n\n"
    "Differences from 06a: both asset types run through one parametrized loop; the loss "
    "grid uses the same bounds but a slightly coarser step (Residential has 20,187 exposure "
    "points, so each risk calculation is ~165× the schools workload); and the calibrated "
    "Entity files are written automatically at the end instead of copied by hand."
)

code(
    "from pathlib import Path\n"
    "\n"
    "ENTITY_DIR = \"../data/entity_files_uncalibrated/\"\n"
    "CALIBRATED_ENTITY_DIR = \"../data/entity_files_calibrated/\"\n"
    "\n"
    "HAZARD_DIR = \"../data/hazard/\"\n"
    "HAZARD_FILE = \"Brazil_Porto_Alegre_2024_duration.tif\"\n"
    "haz_filepath = Path(HAZARD_DIR) / HAZARD_FILE\n"
    "\n"
    "OBSERVATIONS_DIR = \"../data/observations/\"\n"
    "OBSERVATIONS_FILE = \"observations_2024.csv\"\n"
    "observations_filepath = Path(OBSERVATIONS_DIR) / OBSERVATIONS_FILE\n"
    "\n"
    "# Per-asset-type configuration\n"
    "ASSET_CONFIGS = {\n"
    "    \"Residential\": {\n"
    "        \"entity_file\": \"Porto_Alegre_BRAZIL_Entity_Floods_Residential.xlsx\",\n"
    "        \"calibrated_file\": \"Porto_Alegre_BRAZIL_Entity_Floods_Residential_calibrated.xlsx\",\n"
    "        \"impf_id_loss\": 101,\n"
    "        \"impf_id_affected\": 102,\n"
    "        \"obs_asset_type\": \"Residential\",\n"
    "        \"count_unit\": \"number of residential buildings\",\n"
    "    },\n"
    "    \"Companies\": {\n"
    "        \"entity_file\": \"Porto_Alegre_BRAZIL_Entity_Floods_Companies.xlsx\",\n"
    "        \"calibrated_file\": \"Porto_Alegre_BRAZIL_Entity_Floods_Companies_calibrated.xlsx\",\n"
    "        \"impf_id_loss\": 201,\n"
    "        \"impf_id_affected\": 202,\n"
    "        \"obs_asset_type\": \"Business: All\",\n"
    "        \"count_unit\": \"number of businesses\",\n"
    "    },\n"
    "}"
)

md("## Load the components of risk")

code(
    "import copy\n"
    "from climada.entity import Entity\n"
    "\n"
    "impf_column = \"impf_FL\"\n"
    "\n"
    "# Same helper as 06a: re-read the Entity with the 'count' column as value when\n"
    "# calibrating against numbers of affected buildings\n"
    "def read_entity(path, value_column):\n"
    "    entity = Entity.from_excel(path)\n"
    "    if value_column == \"value\":\n"
    "        return entity\n"
    "    new_gdf = entity.exposures.gdf.copy()\n"
    "    new_gdf[\"value\"] = new_gdf[value_column]\n"
    "    entity.exposures.set_gdf(new_gdf)\n"
    "    return entity\n"
    "\n"
    "entities = {}\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    path = Path(ENTITY_DIR) / cfg[\"entity_file\"]\n"
    "\n"
    "    entity_usd = read_entity(path, value_column=\"value\")\n"
    "    entity_usd.exposures.ref_year = 2025\n"
    "    entity_usd.exposures.value_unit = \"USD\"\n"
    "    entity_usd.exposures.description = f\"{asset}: economic value\"\n"
    "\n"
    "    entity_count = read_entity(path, value_column=\"count\")\n"
    "    entity_count.exposures.ref_year = 2025\n"
    "    entity_count.exposures.value_unit = cfg[\"count_unit\"]\n"
    "    entity_count.exposures.description = f\"{asset}: count\"\n"
    "\n"
    "    entities[asset] = {\"usd\": entity_usd, \"count\": entity_count}\n"
    "    print(\n"
    "        f\"{asset}: {len(entity_usd.exposures.gdf)} points, \"\n"
    "        f\"total value {entity_usd.exposures.gdf['value'].sum():,.0f} USD, \"\n"
    "        f\"total count {entity_count.exposures.gdf['value'].sum():,.0f}\"\n"
    "    )"
)

md("### Load Hazard data (2024 flood duration reconstruction)")

code(
    "import numpy as np\n"
    "from climada.hazard import Hazard\n"
    "\n"
    "haz = Hazard.from_raster(\n"
    "    files_intensity=haz_filepath,\n"
    "    attrs={\n"
    "        \"unit\": \"days\",\n"
    "        \"event_name\": [\"2024 Flood\"],\n"
    "        \"frequency\": np.array([1]),\n"
    "    },\n"
    "    haz_type=\"FL\",\n"
    ")\n"
    "\n"
    "for asset in ASSET_CONFIGS:\n"
    "    for kind in (\"usd\", \"count\"):\n"
    "        exp = entities[asset][kind].exposures\n"
    "        exp.assign_centroids(hazard=haz, overwrite=True)\n"
    "        assert exp.gdf[\"centr_FL\"].isna().sum() == 0, (\n"
    "            f\"{asset}/{kind}: some exposures have no assigned hazard centroid\"\n"
    "        )\n"
    "print(\"Centroids assigned for all entities\")"
)

md(
    "### Load observations\n\n"
    "As in 06a we use the Porto Alegre dashboard for 'Affected' counts and the IDB "
    "post-disaster assessment for economic losses, converting BRL to USD at the 2024 "
    "exchange rate."
)

code(
    "import pandas as pd\n"
    "\n"
    "BRL_to_USD = 0.18  # 2024 exchange rate, as in 06a\n"
    "\n"
    "obs = pd.read_csv(observations_filepath)\n"
    "targets = {}\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    obs_asset = obs[obs[\"Asset type\"] == cfg[\"obs_asset_type\"]]\n"
    "\n"
    "    obs_affected = obs_asset[\n"
    "        (obs_asset[\"Impact type\"] == \"Affected\") & (obs_asset[\"Source\"] == \"Porto Alegre\")\n"
    "    ][\"Value\"]\n"
    "    assert len(obs_affected) == 1, f\"{asset}: expected one 'Affected' observation\"\n"
    "\n"
    "    obs_loss = obs_asset[\n"
    "        (obs_asset[\"Impact type\"] == \"Economic loss\") & (obs_asset[\"Source\"] == \"IDB\")\n"
    "    ][\"Value\"]\n"
    "    assert len(obs_loss) == 1, f\"{asset}: expected one 'Economic loss' observation\"\n"
    "\n"
    "    targets[asset] = {\n"
    "        \"affected\": float(obs_affected.values[0]),\n"
    "        \"loss_usd\": float(obs_loss.values[0]) * BRL_to_USD,\n"
    "    }\n"
    "\n"
    "    exp_count = entities[asset][\"count\"].exposures.gdf[\"value\"].sum()\n"
    "    exp_value = entities[asset][\"usd\"].exposures.gdf[\"value\"].sum()\n"
    "    print(f\"--- {asset} ---\")\n"
    "    print(f\"Observed affected: {targets[asset]['affected']:,.0f} | in Exposures: {exp_count:,.0f}\")\n"
    "    print(f\"Observed loss:     {targets[asset]['loss_usd']:,.0f} USD | total exposed value: {exp_value:,.0f} USD\")"
)

md("## Reusable calibration methods (as in 06a)")

code(
    "import logging\n"
    "from climada.entity import ImpactFunc, ImpactFuncSet\n"
    "from climada.engine import ImpactCalc\n"
    "\n"
    "def risk_calc(entity, hazard):\n"
    "    entity.exposures.assign_centroids(hazard=hazard, overwrite=False)\n"
    "    imp = ImpactCalc(entity.exposures, entity.impact_funcs, hazard).impact(\n"
    "        save_mat=False, assign_centroids=False\n"
    "    )\n"
    "    return imp, imp.at_event[0]\n"
    "\n"
    "def cost_function(modelled, observed):\n"
    "    return np.abs((modelled - observed) / observed) * 100\n"
    "\n"
    "def replace_impact_function(entity, new_impf):\n"
    "    entity_new = copy.deepcopy(entity)\n"
    "    entity_new.impact_funcs = ImpactFuncSet([new_impf])\n"
    "    gdf_new = copy.deepcopy(entity_new.exposures.gdf)\n"
    "    gdf_new[impf_column] = new_impf.id\n"
    "    entity_new.exposures.set_gdf(gdf_new)\n"
    "    return entity_new\n"
    "\n"
    "def step_function(step, fun_id=None, name=None):\n"
    "    return ImpactFunc.from_step_impf(\n"
    "        intensity=(0, step, 90),\n"
    "        mdd=(0, 1),\n"
    "        paa=(1, 1),\n"
    "        haz_type=\"FL\",\n"
    "        impf_id=fun_id,\n"
    "        intensity_unit=\"days\",\n"
    "        name=name,\n"
    "    )\n"
    "\n"
    "def scale_impf(impf, max_damage, max_intensity):\n"
    "    impf_new = copy.deepcopy(impf)\n"
    "    impf_new.intensity = impf_new.intensity * (max_intensity / impf.intensity.max())\n"
    "    impf_new.mdd = np.clip(impf_new.mdd * (max_damage / impf.mdd.max()), 0, 1)\n"
    "    return impf_new\n"
    "\n"
    "def quiet_logs(quiet=True):\n"
    "    level = logging.WARNING if quiet else logging.INFO\n"
    "    logging.getLogger(\"climada.engine.impact_calc\").setLevel(level)\n"
    "    logging.getLogger(\"climada.entity.exposures.base\").setLevel(level)\n"
    "\n"
    "def get_best_result(results_df):\n"
    "    return dict(results_df.loc[results_df[\"cost\"].idxmin(), :])"
)

md(
    "## Affected calibration: step functions\n\n"
    "As with schools in 06a, 'affected' is binary per exposure point and we search for the "
    "flood-duration threshold that best reproduces the reported affected counts."
)

code(
    "step_values = np.arange(0.25, 10.25, 0.5)\n"
    "affected_results = {}\n"
    "\n"
    "quiet_logs(True)\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    entity_count = entities[asset][\"count\"]\n"
    "    target = targets[asset][\"affected\"]\n"
    "    default_impf = entity_count.impact_funcs.get_func(\n"
    "        haz_type=\"FL\", fun_id=cfg[\"impf_id_affected\"]\n"
    "    )\n"
    "\n"
    "    rows = []\n"
    "    for step in step_values:\n"
    "        impf_new = step_function(step, fun_id=cfg[\"impf_id_affected\"], name=default_impf.name)\n"
    "        entity_new = replace_impact_function(entity_count, impf_new)\n"
    "        _, modelled = risk_calc(entity_new, haz)\n"
    "        rows.append({\"step\": step, \"modelled\": modelled, \"cost\": cost_function(modelled, target)})\n"
    "    results_df = pd.DataFrame(rows)\n"
    "    best = get_best_result(results_df)\n"
    "    affected_results[asset] = {\"results\": results_df, \"best\": best}\n"
    "    print(\n"
    "        f\"{asset}: best step = {best['step']:.2f} days -> modelled \"\n"
    "        f\"{best['modelled']:,.0f} affected vs observed {target:,.0f} \"\n"
    "        f\"(cost {best['cost']:.1f}%)\"\n"
    "    )\n"
    "quiet_logs(False)"
)

md(
    "## Economic loss calibration: scaling the first-guess curves\n\n"
    "Same 2-D grid as 06a (bounds unchanged), with a coarser step because each Residential "
    "risk calculation covers 20,187 points. As in 06a, a single loss observation means a "
    "whole family of (max intensity, max damage) pairs fit almost perfectly — the grid "
    "search maps that family and an expert-judgement filter picks from it."
)

code(
    "parameter_space = {\n"
    "    \"max_intensity\": np.arange(0.25, 80.1, 1.5),   # 06a used step 0.75\n"
    "    # 06a searched max_damage in [0.5, 1.2]. That range cannot fit Residential or\n"
    "    # Companies: unlike the 122 high-value schools (observed loss = 40% of exposed\n"
    "    # value), these exposure sets are far broader than the reported losses\n"
    "    # (Residential: 212M USD observed vs 69.3bn exposed, i.e. 0.3%), so the\n"
    "    # effective damage cap must be allowed to go much lower.\n"
    "    \"max_damage\": np.arange(0.01, 1.21, 0.025),\n"
    "}\n"
    "\n"
    "loss_results = {}\n"
    "quiet_logs(True)\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    entity_usd = entities[asset][\"usd\"]\n"
    "    target = targets[asset][\"loss_usd\"]\n"
    "    impf_orig = entity_usd.impact_funcs.get_func(haz_type=\"FL\", fun_id=cfg[\"impf_id_loss\"])\n"
    "\n"
    "    rows = []\n"
    "    for max_damage in parameter_space[\"max_damage\"]:\n"
    "        for max_intensity in parameter_space[\"max_intensity\"]:\n"
    "            impf_new = scale_impf(impf_orig, max_damage, max_intensity)\n"
    "            entity_new = replace_impact_function(entity_usd, impf_new)\n"
    "            _, modelled = risk_calc(entity_new, haz)\n"
    "            rows.append({\n"
    "                \"max_damage\": max_damage,\n"
    "                \"max_intensity\": max_intensity,\n"
    "                \"modelled\": modelled,\n"
    "                \"cost\": cost_function(modelled, target),\n"
    "            })\n"
    "    results_df = pd.DataFrame(rows)\n"
    "    loss_results[asset] = {\"results\": results_df, \"impf_orig\": impf_orig}\n"
    "    print(f\"--- {asset}: top 5 fits ---\")\n"
    "    print(results_df.sort_values(\"cost\").head(5).to_string(index=False))\n"
    "quiet_logs(False)"
)

md(
    "### Expert-judgement choice\n\n"
    "06a filtered the schools family with `max_damage > 0.7` (several schools were fully "
    "rebuilt) and `max_intensity < 30` days. The first criterion does **not** transfer "
    "here: the Residential exposure is a whole-city grid whose total value (69.3bn USD) "
    "dwarfs the reported loss (212M USD, ~0.3%), and the Companies observation (439M USD) "
    "is ~12% of its exposure — so the *effective* damage cap of the calibrated curves must "
    "be far below 70% to compensate for the mismatch between broad exposure datasets and "
    "loss totals (the same data-compatibility issue 06a discusses for schools counts). We "
    "keep only the saturation criterion (`max_intensity < 30`: impacts stop growing within "
    "a month of flooding) and take the best fit inside it, reporting the unfiltered best "
    "for comparison."
)

code(
    "import matplotlib.pyplot as plt\n"
    "\n"
    "chosen_impfs = {}\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    results_df = loss_results[asset][\"results\"]\n"
    "    impf_orig = loss_results[asset][\"impf_orig\"]\n"
    "\n"
    "    best_unfiltered = get_best_result(results_df)\n"
    "    filtered = results_df[results_df[\"max_intensity\"] < 30]\n"
    "    best = get_best_result(filtered)\n"
    "    print(\n"
    "        f\"{asset}: unfiltered best cost {best_unfiltered['cost']:.2f}% \"\n"
    "        f\"(max_damage={best_unfiltered['max_damage']:.3f}, \"\n"
    "        f\"max_intensity={best_unfiltered['max_intensity']:.2f})\"\n"
    "    )\n"
    "\n"
    "    # Fine 1-D refinement of max_damage around the coarse-grid best (modelled loss\n"
    "    # is monotonic in max_damage, so a fine sweep at fixed max_intensity nails it)\n"
    "    quiet_logs(True)\n"
    "    fine_values = np.linspace(best[\"max_damage\"] * 0.4, best[\"max_damage\"] * 2.0, 41)\n"
    "    fine_rows = []\n"
    "    for max_damage in fine_values:\n"
    "        impf_new = scale_impf(impf_orig, max_damage, best[\"max_intensity\"])\n"
    "        entity_new = replace_impact_function(entities[asset][\"usd\"], impf_new)\n"
    "        _, modelled = risk_calc(entity_new, haz)\n"
    "        fine_rows.append({\n"
    "            \"max_damage\": max_damage,\n"
    "            \"max_intensity\": best[\"max_intensity\"],\n"
    "            \"cost\": cost_function(modelled, targets[asset][\"loss_usd\"]),\n"
    "        })\n"
    "    quiet_logs(False)\n"
    "    best = get_best_result(pd.DataFrame(fine_rows))\n"
    "\n"
    "    impf_chosen = scale_impf(impf_orig, best[\"max_damage\"], best[\"max_intensity\"])\n"
    "    impf_chosen.id = cfg[\"impf_id_loss\"]\n"
    "    impf_chosen.name = impf_orig.name\n"
    "    chosen_impfs[asset] = impf_chosen\n"
    "\n"
    "    entity_check = replace_impact_function(entities[asset][\"usd\"], impf_chosen)\n"
    "    _, modelled = risk_calc(entity_check, haz)\n"
    "    cost = cost_function(modelled, targets[asset][\"loss_usd\"])\n"
    "    print(\n"
    "        f\"{asset}: chosen max_damage={best['max_damage']:.2f}, \"\n"
    "        f\"max_intensity={best['max_intensity']:.2f} -> modelled \"\n"
    "        f\"{modelled:,.0f} USD vs observed {targets[asset]['loss_usd']:,.0f} USD \"\n"
    "        f\"(cost {cost:.2f}%)\"\n"
    "    )\n"
    "\n"
    "    fig, axis = plt.subplots(figsize=(7, 3.5))\n"
    "    axis.plot(impf_orig.intensity, impf_orig.mdd, color=\"grey\", linestyle=\"--\", label=\"First guess\")\n"
    "    axis.plot(impf_chosen.intensity, impf_chosen.mdd, color=\"red\", label=\"Calibrated\")\n"
    "    axis.set_xlabel(\"Flood duration (days)\")\n"
    "    axis.set_ylabel(\"Mean damage degree\")\n"
    "    axis.set_xlim((0, 40))\n"
    "    axis.set_ylim((0, 1.05))\n"
    "    axis.legend()\n"
    "    axis.set_title(f\"{asset}: loss impact function\")\n"
    "    plt.show()\n"
    "    plt.close(fig)"
)

md(
    "## Write the calibrated Entity files\n\n"
    "Unlike 06a (which prints a table to copy into Excel by hand), we write the calibrated "
    "files directly: copy the uncalibrated workbook, replace the `impact_functions` sheet "
    "rows with the calibrated loss curve and affected step function, and verify by "
    "re-reading with CLIMADA and re-running the risk calculation."
)

code(
    "import shutil\n"
    "import openpyxl\n"
    "\n"
    "Path(CALIBRATED_ENTITY_DIR).mkdir(exist_ok=True)\n"
    "\n"
    "for asset, cfg in ASSET_CONFIGS.items():\n"
    "    src = Path(ENTITY_DIR) / cfg[\"entity_file\"]\n"
    "    dst = Path(CALIBRATED_ENTITY_DIR) / cfg[\"calibrated_file\"]\n"
    "    shutil.copyfile(src, dst)\n"
    "\n"
    "    impf_loss = chosen_impfs[asset]\n"
    "    impf_affected = step_function(\n"
    "        affected_results[asset][\"best\"][\"step\"],\n"
    "        fun_id=cfg[\"impf_id_affected\"],\n"
    "        name=entities[asset][\"count\"].impact_funcs.get_func(\n"
    "            haz_type=\"FL\", fun_id=cfg[\"impf_id_affected\"]\n"
    "        ).name,\n"
    "    )\n"
    "\n"
    "    wb = openpyxl.load_workbook(dst)\n"
    "    ws = wb[\"impact_functions\"]\n"
    "    header = [c.value for c in ws[1]]\n"
    "    assert header[:7] == [\n"
    "        \"impact_fun_id\", \"intensity\", \"mdd\", \"paa\", \"peril_id\", \"name\", \"intensity_unit\"\n"
    "    ], f\"Unexpected impact_functions header: {header}\"\n"
    "\n"
    "    ws.delete_rows(2, ws.max_row)\n"
    "    for impf in (impf_loss, impf_affected):\n"
    "        for inten, mdd, paa in zip(impf.intensity, impf.mdd, impf.paa):\n"
    "            ws.append([impf.id, float(inten), float(mdd), float(paa), \"FL\", impf.name, \"days\"])\n"
    "    wb.save(dst)\n"
    "\n"
    "    # Verify: re-read with CLIMADA and reproduce the calibrated numbers\n"
    "    entity_verify = read_entity(dst, value_column=\"value\")\n"
    "    entity_verify.exposures.ref_year = 2025\n"
    "    entity_verify.exposures.value_unit = \"USD\"\n"
    "    _, modelled_verify = risk_calc(entity_verify, haz)\n"
    "    cost_verify = cost_function(modelled_verify, targets[asset][\"loss_usd\"])\n"
    "    assert cost_verify < 20, (\n"
    "        f\"{asset}: calibrated file reproduces {modelled_verify:,.0f} USD, \"\n"
    "        f\"{cost_verify:.1f}% from observations — check the export\"\n"
    "    )\n"
    "    print(f\"{asset}: wrote {dst.name}; re-read losses {modelled_verify:,.0f} USD ({cost_verify:.2f}% from obs)\")"
)

md(
    "## Conclusions\n\n"
    "- As with schools in 06a, the *affected* counts cannot exceed the number of exposure "
    "points that experience any flooding at all, so the step functions saturate at the "
    "lowest thresholds and may still underestimate reported counts — the definitions of "
    "'affected' in the observations are broader than 'was flooded' in the model.\n"
    "- The *loss* calibrations fit a family of near-equivalent curves; the choice inside "
    "that family (saturation < 30 days; effective damage cap free, and necessarily far "
    "below the schools' 70% because these exposure sets are much broader than the loss "
    "totals) is expert judgement and should be revisited with local input.\n"
    "- The calibrated Entity files are written to `data/entity_files_calibrated/` and "
    "verified by re-reading them with CLIMADA and reproducing the calibrated losses."
)

nb = nbformat.v4.new_notebook(cells=cells)
nb.metadata["kernelspec"] = {
    "display_name": "Python 3",
    "language": "python",
    "name": "python3",
}
nbformat.write(nb, DST)
print(f"Wrote {DST} with {len(cells)} cells")
